// This file was auto-generated by ML.NET Model Builder. 

using System;
using SpendScorePredictorML.Model;

namespace SpendScorePredictorML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                Gender = @"Male",
                Age = 29F,
                AnnualIncome = 15F,
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual SpendingScore with predicted SpendingScore from sample data...\n\n");
            Console.WriteLine($"Gender: {sampleData.Gender}");
            Console.WriteLine($"Age: {sampleData.Age}");
            Console.WriteLine($"AnnualIncome: {sampleData.AnnualIncome}");
            Console.WriteLine($"\n\nPredicted SpendingScore: {predictionResult.Score}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
