apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/part-of: microservicesapp
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: rabbitmq
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rabbitmq
        app.kubernetes.io/part-of: microservicesapp
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 5672
            - containerPort: 15672

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/part-of: microservicesapp
spec:
  ports:
    - port: 5672
      protocol: TCP
      targetPort: 5672
  selector:
    app.kubernetes.io/name: rabbitmq
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-mui
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/part-of: microservicesapp
spec:
  type: NodePort
  ports:
    - port: 15672
      protocol: TCP
      targetPort: 15672
      nodePort: 30072
  selector:
    app.kubernetes.io/name: rabbitmq
